### ISSUE TITLE
Panic  when parsing  AIS messages

### ISSUE THREAD

**Issue by tiphaineruy** [zaari/nmea-parser#19]
Code panics when parsing messages with invalid payload:
ex: Type26
!AIVDM,1,1,,,Jl@bhbmCU`:lwOd0,0*48

( I'm using this Lib to parse huge files, thus I need to avoid panic and correctly propagate errors)

But this isn't the only type it can panic on.  All messages with valid decode but with invalid payload length will panic because of the way byteslices are extracted:
> BitVec::from_bitslice(...
Which panics.

Although this message is invalid, valid information can be extracted from it:
If you paste it here: http://ais.tbsalling.dk/ you get everything up to the data.

Proposals:
- I could just pr  fixes on each message for which I get a panic and go from there...
- Quick fix: add test on length when parsing  ( wrapp all  ::from_bitslice with a length check and throw error on invalid length )
- Refactor with a parsing lib such as https://github.com/Geal/nom 

I could spend some time working on that but I guess it really depend on the status of the lib.
How do you this this lib future ? Have any plan for it ?

**Comment by zaari** [comment]
The bug is foxed for message types 26 and 27. Now, payload lower bound violations are simply ignored and an empty payload returned. If you prefer throwing an error, that can be considered too. I would prefer keeping dependencies of this crate at minimum.
