### ISSUE TITLE
Thoughts on rustfmt

### ISSUE THREAD

**Issue by wezm** [zaari/nmea-parser#7]
I notice that the code isn't formatted with [rustfmt](https://github.com/rust-lang/rustfmt), the official Rust code formatter. I was wondering if you'd be open to a PR that formatted the code with it? The benefit in my eyes is that you can just let the tool take care of it, knowing that it will be consistent with other code in the Rust ecosystem. I notice that in some places you've formatted code a particular way (tables of bits for example). If I were to format the project I'd try to make sure that things like this were preserved.

**Comment by zaari** [comment]
I'm in favor of unified coding style, but there are also cases where some deviations make the code more readable. I'll run the formatter later by myself and change the sections I prefer to keep "non-consistent". Thanks for pointing this out.

**Comment by wezm** [comment]
Fantastic, thanks for doing that.
